### ISSUE TITLE
Dependency Managment and Travis.

### ISSUE THREAD

**Issue by Keridos** [Keridos/FloodLights#81]
Currently 1.12 EnderIO is not on any maven. Could we somehow make this work properly? I am in touch with the EnderIO Devs to figure out a solution for this.

**Comment by drzpk** [comment]
Actually I have already removed EnderIO dependency and Jenkins works fine since then. However, the most recent build on Travis has failed due to some unresolved dependencies ([HERE](https://travis-ci.org/Keridos/FloodLights/builds/423348112?utm_source=github_status&utm_medium=notification)). I'm going to look into it soon.

**Comment by Keridos** [comment]
https://github.com/SleepyTrousers/EnderIO/pull/4856

And I will take a look at Jenkins, apparently they deprecate the old service integration. Moved it to the new github app. Lets see if this works in the future.

**Comment by Keridos** [comment]
EnderIO has merged the commit, so you can get the newer versions (nightly builds) via their maven.
